services:
  - type: web
    name: cmtch
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: cmtch-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

  - type: pserv
    name: cmtch-db
    plan: free
    env: postgresql
    ipAllowList: []
