services:
  - type: web
    name: cmtch
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true
